{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.postgresServiceName" . }}
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
