services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: hackaton-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env
    # Pokud používáte RDS, DATABASE_URL v .env musí mířit na AWS adresu

  frontend:
    build:
      context: ./apps/frontend/frontend
      dockerfile: Dockerfile
    container_name: hackaton-frontend
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - backend

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    container_name: hackaton-admin
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend
