{{- if .Values.linkerd.enabled }}
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: {{ include "menu.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "menu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "menu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  port: http
  proxyProtocol: HTTP/1
{{- end }}
