{{- if .Values.linkerd.enabled }}
---
# Allow any meshed service in this namespace.
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: {{ include "menu.fullname" . }}-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "menu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  identities:
    - "*.{{ .Release.Namespace }}.serviceaccount.cluster.local"
---
# Allow traffic from the (possibly un-meshed) ingress controller.
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: {{ include "menu.fullname" . }}-ingress-network
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "menu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  networks:
    - cidr: 0.0.0.0/0
    - cidr: ::/0
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ include "menu.fullname" . }}-allow-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "menu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: {{ include "menu.fullname" . }}-http
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: MeshTLSAuthentication
      name: {{ include "menu.fullname" . }}-mesh
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ include "menu.fullname" . }}-allow-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "menu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: {{ include "menu.fullname" . }}-http
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: NetworkAuthentication
      name: {{ include "menu.fullname" . }}-ingress-network
{{- end }}
