replicaCount: 1

image:
  repository: jiwi/objevplzen
  tag: backend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  nodeEnv: production
  jwtSecret: ""
  googlePlacesApiKey: ""

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    username: ""
    password: ""
    database: ""
  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi

resources: {}
