replicaCount: 1

image:
  repository: jiwi/objevplzen
  tag: menu
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3003

env:
  nextPublicApiUrl: "http://backend:3000/api"

resources: {}
